import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="flex h-screen items-center justify-center">
      <Head>
        <title>Next JS Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <h1 className="text-5xl">טוב הנה נקסט ריק מוכן</h1>
    </div>
  );
};

export default Home;
